apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}-frontend
spec:
  selector:
    app: {{ .Values.fullnameOverride }}-frontend
  ports:
    - port: {{ .Values.sample-node-app-frontend.image.port }}
      targetPort: {{ .Values.sample-node-app-frontend.image.port }}
  type: {{ .Values.service.type }}