apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}-backend
spec:
  selector:
    app: {{ .Values.fullnameOverride }}-backend
  ports:
    - port: {{ .Values.sample_node_app_backend.image.port }}
      targetPort: {{ .Values.sample_node_app_backend.image.port }}
  type: {{ .Values.service.type }}