apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}-db
spec:
  selector:
    app: {{ .Values.fullnameOverride }}-db
  ports:
    - port: {{ .Values.db.image.port }}
      targetPort: {{ .Values.db.image.port }}
  type: {{ .Values.service.type }}