name: Manifest auto updater (non-production)

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        type: string
      version:
        required: true
        type: string
      appName:
        required: true
        type: string

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Update Frontend image version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: '/values.yaml'
          propertyPath: '${{ github.event.inputs.appName }}_frontend.image.tag'
          value: ${{ github.event.inputs.version }}
          branch: ${{ github.event.inputs.ref }}
          targetBranch: main
          masterBranchName: main
          createPR: true
          message: 'Update Image Version to ${{ github.event.inputs.version }}'
          workDir: 'charts/${{ github.event.inputs.appName }}'
          
      - name: Update Backend image version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'values.yaml'
          propertyPath: '${{ github.event.inputs.appName }}_backend.image.tag'
          value: ${{ github.event.inputs.version }}
          branch: ${{ github.event.inputs.ref }}
          targetBranch: main
          masterBranchName: main
          createPR: true
          message: 'Update Image Version to ${{ github.event.inputs.version }}'
          workDir: 'charts/${{ github.event.inputs.appName }}'
