name: Manifest auto updater (non-production)

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        type: string
      version:
        required: true
        type: string
      appName:
        required: true
        type: string
      appComponent:
        required: false
        type: string

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Check and concatenate application name and component
        id: concat
        run: |
          if [ -n "${{ github.event.inputs.appComponent }}" ]; then
            echo "::set-output name=concatenatedMessageString::Update ${{ github.event.inputs.appName }}_${{ github.event.inputs.appComponent }} image Version to ${{ github.event.inputs.version }}"
            echo "::set-output name=concatenateComponentPath::${{ github.event.inputs.appName }}_${{ github.event.inputs.appComponent }}"
          else
            echo "::set-output name=concatenatedMessageString::Update ${{ github.event.inputs.appName }} image Version to ${{ github.event.inputs.version }}"
            echo "::set-output name=concatenateComponentPath::${{ github.event.inputs.appName }}"
          fi

      - name: Update image version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'values.yaml'
          propertyPath: '${{ steps.concat.outputs.concatenateComponentPath }}.image.tag'
          value: ${{ github.event.inputs.version }}
          branch: '${{ github.event.inputs.appName }}-${{ github.event.inputs.ref }}'
          targetBranch: main
          masterBranchName: main
          createPR: true
          message: '${{ steps.concat.outputs.concatenatedMessageString }}'
          workDir: 'charts/${{ github.event.inputs.appName }}'
