name: Manifest auto updater (non-production)

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        type: string
      version:
        required: true
        type: string
      appName:
        required: true
        type: string
      appComponent:
        required: false
        type: string

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Check and concatenate application name and component
        id: concat
        run: |
          if [ -n "${{ github.event.inputs.appComponent }}" ]; then
            echo "CONCATENATEDMESSAGESTRING='Update ${{ github.event.inputs.appName }}_${{ github.event.inputs.appComponent }} image Version to ${{ github.event.inputs.version }}'" >> $GITHUB_ENV
            echo "CONCATENATEDCOMPONENTPATH='${{ github.event.inputs.appName }}_${{ github.event.inputs.appComponent }}'" >> $GITHUB_ENV
          else
            echo "CONCATENATEDMESSAGESTRING='Update ${{ github.event.inputs.appName }} image Version to ${{ github.event.inputs.version }}'" >> $GITHUB_ENV
            echo "CONCATENATEDCOMPONENTPATH='${{ github.event.inputs.appName }}'" >> $GITHUB_ENV
          fi

      - name: Set docker image version
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.${{ env.CONCATENATEDCOMPONENTPATH }}.image.tag = "${{ github.event.inputs.version }}"' 'charts/${{ github.event.inputs.appName }}/values.yaml'

      - name: Get chart current version
        uses: mikefarah/yq@master
        id: get_chart_version
        with:
          cmd: yq '.version' charts/${{ github.event.inputs.appName }}/Chart.yaml

      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.1.0
        with:
          current-version: '${{ steps.get_chart_version.outputs.result }}'
          version-fragment: 'bug'
          
      - name: Update Chart version
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.version = "${{ steps.bump_version.outputs.next-version }}"' 'charts/${{ github.event.inputs.appName }}/Chart.yaml'
          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update report
          branch: '${{ github.event.inputs.appName }}-${{ github.event.inputs.ref }}'
          delete-branch: true
          base: main
          title: ${{ env.CONCATENATEDMESSAGESTRING }}
